baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'My Blog'
theme = 'paper'

[params]
  color = 'linen'
  name = 'Your Name'
  bio = 'Cybersecurity Enthusiast'
  github = 'yourgithub'
  rss = true

