baseURL = 'https://slvignesh05.github.io/my-blog/'
languageCode = 'en-us'
title = 'My Blog'
theme = 'paper'

[params]
  color = 'linen'
  name = 'S.Lakshmi Vignesh'
  bio = 'A Cybersecurity & Data Science student who likes to break web applications and look into authentication bugs apart from that I like to build random intriguing web apps'
  github = 'slvignesh05'
  rss = true
