baseURL = 'https://slvignesh05.github.io/my-blog/'
languageCode = 'en-us'
title = 'My Blog'
theme = 'paper'

[params]
  color = 'linen'
  name = 'Your Name'
  bio = 'Cybersecurity Enthusiast'
  github = 'slvignesh05'
  rss = true
